### ISSUE TITLE
 error on state_location_payload_key in version 0.5.2

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-Shims#21]
https://forums.indigodomo.com/viewtopic.php?f=316&t=25195

**Comment by FlyingDiver** [comment]
```
MQTT Shims Error Ring Alarm Basestation Info: error on state_location_payload_key, aborting
MQTT Shims Error Ring Alarm Keypad Entryway: error on state_location_payload_key, aborting
MQTT Shims Error Ring Alarm Keypad Bedroom: error on state_location_payload_key, aborting
MQTT Shims Error Ring Alarm Keypad Basement: error on state_location_payload_key, aborting
MQTT Shims Error Ring Alarm ZWave Extender: error on state_location_payload_key, aborting
MQTT Shims Error Ring Alarm ZWave Extender Basement: error on state_location_payload_key, aborting
```

**Comment by FlyingDiver** [comment]
```
   MQTT Shims                      
message_type: '##RingAlarm##'
props:
    SupportsBatteryLevel: true
    battery_payload_key: topics.info.topics.state.payload.batteryLevel
    state_dict_payload_key: topics.info.topics.state.payload
    state_location: payload
    state_location_payload_type: json
    uid_location: topic
    uid_location_topic_field: '3'
trigger:
    match_list: '["Match: ring", "Match:ACCOUNT_GUID, "Match: alarm", "Any: ", "End: "]'
    queueMessage: true
type: shimGeneric
```
