### ISSUE TITLE
Error message on device state update

### ISSUE THREAD

**Issue by berkinet** [FlyingDiver/Indigo-Shims#25]
Indigo 2022.1.2
Device template:
```
24 Oct 2022 at 17:16:26
   MQTT Shims                      
message_type: '##LinkTap2##'
props:
    SupportsBatteryLevel: true
    SupportsEnergyMeter: true
    SupportsEnergyMeterCurPower: true
    battery_payload_key: dev_stat.battery
    energy_payload_key: dev_stat.speed
    power_payload_key: dev_stat.volume
    shimSensorSubtype: Power
    state_dict_payload_key: .
    state_location: payload
    state_location_payload_key: dev_stat.is_watering
    state_location_payload_type: json
    state_location_topic_field: '0'
    uid_location: topic
    uid_location_topic_field: '3'
trigger:
    match_list: '["Any: 064ED91D004B1200_2"]'
    queueMessage: true
type: shimOnOffSensor
```
Logged error:
```
24 Oct 2022 at 17:16:42
   MQTT Connector Debug            CM MQTT Connector: processReceivedMessage: cm/uplink/topic/064ED91D004B1200_2, payload: {"cmd":3,"gw_id":"5150D91D004B1200","dev_stat":{"dev_id":"064ED91D004B1200_2","plan_mode":5,"plan_sn":281531291,"is_rf_linked":true,"is_flm_plugin":true,"is_fall":false,"is_broken":false,"is_cutoff":false,"is_leak":false,"is_clog":false,"signal":83,"battery":100,"child_lock":0,"is_manual_mode":false,"is_watering":false,"is_final":true,"total_duration":30,"remain_duration":0,"speed":0.00,"volume":0.00,"volume_limit":0.00,"failsafe_duration":0}}
   MQTT Connector Debug            LinkTap test: type = topicMatch, broker = 1807946172
   MQTT Connector Debug            LinkTap test: Matching complete, is_match = True
   Trigger                         LinkTap2 test
   MQTT Connector Debug            LinkTap1 test: type = topicMatch, broker = 1807946172
   MQTT Connector Debug            LinkTap1 test: Matching complete, is_match = False
   MQTT Test                       MATCH
   MQTT Shims Debug                message_handler: MQTT message ##LinkTap2## from CM MQTT Connector
   MQTT Shims Debug                LinkTap Asparagus: processMessages: '##LinkTap2##' cm/uplink/topic/064ED91D004B1200_2 -> {"cmd":3,"gw_id":"5150D91D004B1200","dev_stat":{"dev_id":"064ED91D004B1200_2","plan_mode":5,"plan_sn":281531291,"is_rf_linked":true,"is_flm_plugin":true,"is_fall":false,"is_broken":false,"is_cutoff":false,"is_leak":false,"is_clog":false,"signal":83,"battery":100,"child_lock":0,"is_manual_mode":false,"is_watering":false,"is_final":true,"total_duration":30,"remain_duration":0,"speed":0.00,"volume":0.00,"volume_limit":0.00,"failsafe_duration":0}}
   MQTT Shims Debug                LinkTap Asparagus: Raw payload = {"cmd":3,"gw_id":"5150D91D004B1200","dev_stat":{"dev_id":"064ED91D004B1200_2","plan_mode":5,"plan_sn":281531291,"is_rf_linked":true,"is_flm_plugin":true,"is_fall":false,"is_broken":false,"is_cutoff":false,"is_leak":false,"is_clog":false,"signal":83,"battery":100,"child_lock":0,"is_manual_mode":false,"is_watering":false,"is_final":true,"total_duration":30,"remain_duration":0,"speed":0.00,"volume":0.00,"volume_limit":0.00,"failsafe_duration":0}}
   MQTT Shims Debug                LinkTap Asparagus: states_key= .
   MQTT Shims Debug                LinkTap Asparagus: Decoded payload = {'cmd': 3, 'gw_id': '5150D91D004B1200', 'dev_stat': {'dev_id': '064ED91D004B1200_2', 'plan_mode': 5, 'plan_sn': 281531291, 'is_rf_linked': True, 'is_flm_plugin': True, 'is_fall': False, 'is_broken': False, 'is_cutoff': False, 'is_leak': False, 'is_clog': False, 'signal': 83, 'battery': 100, 'child_lock': 0, 'is_manual_mode': False, 'is_watering': False, 'is_final': True, 'total_duration': 30, 'remain_duration': 0, 'speed': 0.0, 'volume': 0.0, 'volume_limit': 0.0, 'failsafe_duration': 0}}
   MQTT Shims Debug                LinkTap Asparagus: states_dict = {'cmd': 3, 'gw_id': '5150D91D004B1200', 'dev_stat': {'dev_id': '064ED91D004B1200_2', 'plan_mode': 5, 'plan_sn': 281531291, 'is_rf_linked': True, 'is_flm_plugin': True, 'is_fall': False, 'is_broken': False, 'is_cutoff': False, 'is_leak': False, 'is_clog': False, 'signal': 83, 'battery': 100, 'child_lock': 0, 'is_manual_mode': False, 'is_watering': False, 'is_final': True, 'total_duration': 30, 'remain_duration': 0, 'speed': 0.0, 'volume': 0.0, 'volume_limit': 0.0, 'failsafe_duration': 0}}
   MQTT Shims Debug                LinkTap Asparagus: adding to states_list: cmd, 3, <class 'int'>
   MQTT Shims Debug                LinkTap Asparagus: adding to states_list: gw_id, 5150D91D004B1200, <class 'str'>
   MQTT Shims Debug                LinkTap Asparagus: adding to states_list: dev_stat, {'dev_id': '064ED91D004B1200_2', 'plan_mode': 5, 'plan_sn': 281531291, 'is_rf_linked': True, 'is_flm_plugin': True, 'is_fall': False, 'is_broken': False, 'is_cutoff': False, 'is_leak': False, 'is_clog': False, 'signal': 83, 'battery': 100, 'child_lock': 0, 'is_manual_mode': False, 'is_watering': False, 'is_final': True, 'total_duration': 30, 'remain_duration': 0, 'speed': 0.0, 'volume': 0.0, 'volume_limit': 0.0, 'failsafe_duration': 0}, <class 'dict'>
   MQTT Shims Debug                LinkTap Asparagus: Updating state to False
   Error                           device "LinkTap Asparagus" state key onOffState not defined (ignoring update request)
   Error                           device "LinkTap Asparagus" state key onOffState not defined (ignoring update request)
```
